name: flutter_baselib
description: dev common lib
version: 0.1.13
homepage: https://gitee.com/SilenceJR/flutter_baselib.git

environment:
  sdk: '>=3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  get: ^4.6.6
  get_storage: ^2.1.1
  logger: ^2.0.2+1

  package_info_plus: ^8.0.2
  image_gallery_saver: ^2.0.3
  permission_handler: ^11.1.0

  url_launcher: ^6.2.2
  date_format: ^2.0.7
  decimal: ^3.0.2

#  cupertino_icons: ^1.0.4
#  collection: ^1.17.2
  #https://pub.dev/packages/get

#  package_info: ^2.0.2
#  flutter_native_image: ^0.0.6+1
#  wechat_assets_picker: ^8.7.0
#  wechat_camera_picker: ^4.0.1
#  image_gallery_saver: ^2.0.3
#  permission_handler: ^11.0.1
#  webview_flutter: ^4.4.2

#  decimal: ^2.3.3
#  date_format: ^2.0.7
#  video_player: ^2.7.1
  #  badges: ^3.1.2
  #  orientation: ^1.3.0
#  app_links: ^3.5.0
#  flustars: ^2.0.1



#  video_compress: #^3.1.0
#    git:
#      url: https://github.com/jonataslaw/VideoCompress.git
#      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter

  dio: any
  get: any
  pull_to_refresh: any


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
